name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.3.0-purplesoft.1
homepage: https://github.com/PurpleSoftSrl/esc_pos_printer

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  charset_converter: ^2.0.0
  esc_pos_utils:
    git:
      url: https://github.com/PurpleSoftSrl/esc_pos_utils.git
      ref: master
  flutter:
    sdk: flutter
  image: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
